set -g status off
set -g mouse off
set -g history-limit 10000
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g escape-time 0
set -g focus-events on
set -g allow-rename off
set -g set-titles off
set -g exit-empty on
set -g detach-on-destroy on
setw -g automatic-rename off
setw -g window-size manual
